
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
production:
  primary:
    <<: *default
    database: dinner_time_production
    username: dinner_time
    password: <%= ENV["DINNER_TIME_DATABASE_PASSWORD"] %>
  primary_shard_one:
    <<: *default
    database: dinner_time_production_shard_one
    username: dinner_time
    password: <%= ENV["DINNER_TIME_DATABASE_PASSWORD"] %>
development:
  primary:
    <<: *default
    database: dinner_time_development
  primary_shard_one:
    <<: *default
    database: dinner_time_development_shard_one
test:
  primary:
    <<: *default
    database: dinner_time_test
  primary_shard_one:
    <<: *default
    database: dinner_time_test_shard_one

